#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/xdesk/xdesk /usr/bin/xdesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/xdesk.service ]; then
			rm /etc/systemd/system/xdesk.service /usr/lib/systemd/system/xdesk.service /usr/lib/systemd/user/xdesk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/xdesk/files/systemd/xdesk.service /usr/lib/systemd/system/xdesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload xdesk.service: Unit xdesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/xdesk.service:10: Executable path is not absolute: pkill -f "xdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/xdesk.service
		fi
		systemctl daemon-reload
		systemctl enable xdesk
		systemctl start xdesk
	fi
fi
